# Generated by Django 3.0.4 on 2020-03-09 06:20

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=posts.models.recipe_image_file_path),
        ),
    ]
