# Generated by Django 3.0.4 on 2020-03-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Posts'},
        ),
    ]
